name: CI

env:
  GRADLE_OPTS: '-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false'
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

on:
  pull_request:
    paths-ignore: [ '**/**.md' ]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-build:
    runs-on: macos-latest
    
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-ci') }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          cache-write-only: ${{ contains(github.event.pull_request.labels.*.name, 'gradle') }}
          cache-read-only: ${{ !contains(github.event.pull_request.labels.*.name, 'gradle') }}

      - name: Code style checks
        run: ./gradlew ktlintCheck detekt

      - name: Run test
        run: ./gradlew test --stacktrace

      - name: Run build
        run: ./gradlew build --stacktrace

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          retention-days: 7
          path: |
            **/build/reports/*

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          retention-days: 7
          path: |
            **/build/test-results/*
