name: docs-deploy
on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  website-deploy:
    environment:
      name: 'github-pages'
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: macos-latest

    if: ${{
      github.event.pull_request.merged &&
      contains(github.event.pull_request.labels.*.name, 'documentation')
      }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Gradle & Build Dokka
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          cache-write-only: false
          cache-read-only: true
          arguments: :sgp:dokkaHtml --no-configuration-cache

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'docs'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
